name: Deploy to Web Server

on:
  push:
    branches:
      - main  # Adjust if your main branch is named differently

jobs:

  build-push-image:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Build Docker image
            run: |
              docker build -t "${{ secrets.DOCKER_REGISTRY }}"/devgains-backend:${{ github.sha }} \
                           --build-arg DB_NAME=${{ secrets.DB_NAME }} \
                           --build-arg DB_USER=${{ secrets.DB_USER }} \
                           --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                           --build-arg DB_HOST=${{ secrets.DB_HOST }} \
                           --build-arg DB_PORT=${{ secrets.DB_PORT }} \
                           . 
          - name: Removing docker login
            run: rm -rf ~/.docker/config.json 
          - name: Login to Docker registry
            run: docker login "https://${{ secrets.DOCKER_REGISTRY }}" -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin <<<"${{ secrets.DOCKER_PASSWORD }}" 
      
          - name: Push Docker image to registry
            run: docker push "${{ secrets.DOCKER_REGISTRY }}"/devgains-backend:${{ github.sha }}
              

  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image

    steps:

      - name: SSH into web server and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin "${{ secrets.DOCKER_REGISTRY }}"
           docker pull "${{ secrets.DOCKER_REGISTRY }}"/devgains-backend:${{ github.sha }}
           docker stop devgains-backend || true
           docker rm devgains-backend || true
           docker run -d --name devgains-backend-node1 -p 3000:3000 "${{ secrets.DOCKER_REGISTRY }}"/devgains-backend:${{ github.sha }}